package xrddev.practiceportal.model.enums;

public enum Department {
    COMPUTER_SCIENCE_AND_ENGINEERING,
    MATHEMATICS,
    PHYSICS,
    CHEMISTRY,
    BIOLOGY,
    ECONOMICS,
    LITERATURE,
    HISTORY,
    PSYCHOLOGY,
    PHILOSOPHY,
    ARCHITECTURE,
    MATERIALS_SCIENCE,
    MEDICINE,
    NURSING,
    SPEECH_LANGUAGE_THERAPY,
    BIOLOGICAL_APPLICATIONS,
    PRIMARY_EDUCATION,
    EARLY_CHILDHOOD_EDUCATION,
    FINE_ARTS,
    ACCOUNTING_FINANCE,
    AGRICULTURE,
    INFORMATICS_TELECOMMUNICATIONS,
    MUSIC_STUDIES,
    EARLY_YEARS_LEARNING_CARE,
    TRANSLATION_INTERPRETING
}